sudo: true
language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo pip install codecov

install: 
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90

script: 
  - ./build_debug.sh
  - ./travis_qmake_gcc_cpp11_debug_gcov_gcov
  - ./get_code_cov.sh
  - codecov
  - ./clean.sh
  - ./build_release.sh
  - ./travis_qmake_gcc_cpp11_debug_gcov

